# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pavel/hermes1d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pavel/hermes1d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavel/hermes1d/CMakeFiles /home/pavel/hermes1d/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavel/hermes1d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hermes1d

# Build rule for target.
hermes1d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hermes1d
.PHONY : hermes1d

# fast build rule for target.
hermes1d/fast:
	$(MAKE) -f src/CMakeFiles/hermes1d.dir/build.make src/CMakeFiles/hermes1d.dir/build
.PHONY : hermes1d/fast

#=============================================================================
# Target rules for targets named first_order_general

# Build rule for target.
first_order_general: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 first_order_general
.PHONY : first_order_general

# fast build rule for target.
first_order_general/fast:
	$(MAKE) -f examples/first_order_general/CMakeFiles/first_order_general.dir/build.make examples/first_order_general/CMakeFiles/first_order_general.dir/build
.PHONY : first_order_general/fast

#=============================================================================
# Target rules for targets named laplace_bc_dirichlet

# Build rule for target.
laplace_bc_dirichlet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplace_bc_dirichlet
.PHONY : laplace_bc_dirichlet

# fast build rule for target.
laplace_bc_dirichlet/fast:
	$(MAKE) -f examples/laplace_bc_dirichlet/CMakeFiles/laplace_bc_dirichlet.dir/build.make examples/laplace_bc_dirichlet/CMakeFiles/laplace_bc_dirichlet.dir/build
.PHONY : laplace_bc_dirichlet/fast

#=============================================================================
# Target rules for targets named laplace_bc_neumann

# Build rule for target.
laplace_bc_neumann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplace_bc_neumann
.PHONY : laplace_bc_neumann

# fast build rule for target.
laplace_bc_neumann/fast:
	$(MAKE) -f examples/laplace_bc_neumann/CMakeFiles/laplace_bc_neumann.dir/build.make examples/laplace_bc_neumann/CMakeFiles/laplace_bc_neumann.dir/build
.PHONY : laplace_bc_neumann/fast

#=============================================================================
# Target rules for targets named laplace_bc_newton

# Build rule for target.
laplace_bc_newton: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplace_bc_newton
.PHONY : laplace_bc_newton

# fast build rule for target.
laplace_bc_newton/fast:
	$(MAKE) -f examples/laplace_bc_newton/CMakeFiles/laplace_bc_newton.dir/build.make examples/laplace_bc_newton/CMakeFiles/laplace_bc_newton.dir/build
.PHONY : laplace_bc_newton/fast

#=============================================================================
# Target rules for targets named laplace_bc_newton2

# Build rule for target.
laplace_bc_newton2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplace_bc_newton2
.PHONY : laplace_bc_newton2

# fast build rule for target.
laplace_bc_newton2/fast:
	$(MAKE) -f examples/laplace_bc_newton2/CMakeFiles/laplace_bc_newton2.dir/build.make examples/laplace_bc_newton2/CMakeFiles/laplace_bc_newton2.dir/build
.PHONY : laplace_bc_newton2/fast

#=============================================================================
# Target rules for targets named system_exp

# Build rule for target.
system_exp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_exp
.PHONY : system_exp

# fast build rule for target.
system_exp/fast:
	$(MAKE) -f examples/system_exp/CMakeFiles/system_exp.dir/build.make examples/system_exp/CMakeFiles/system_exp.dir/build
.PHONY : system_exp/fast

#=============================================================================
# Target rules for targets named system_sin

# Build rule for target.
system_sin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_sin
.PHONY : system_sin

# fast build rule for target.
system_sin/fast:
	$(MAKE) -f examples/system_sin/CMakeFiles/system_sin.dir/build.make examples/system_sin/CMakeFiles/system_sin.dir/build
.PHONY : system_sin/fast

#=============================================================================
# Target rules for targets named system_sin_adapt

# Build rule for target.
system_sin_adapt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_sin_adapt
.PHONY : system_sin_adapt

# fast build rule for target.
system_sin_adapt/fast:
	$(MAKE) -f examples/system_sin_adapt/CMakeFiles/system_sin_adapt.dir/build.make examples/system_sin_adapt/CMakeFiles/system_sin_adapt.dir/build
.PHONY : system_sin_adapt/fast

#=============================================================================
# Target rules for targets named system_pendulum

# Build rule for target.
system_pendulum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_pendulum
.PHONY : system_pendulum

# fast build rule for target.
system_pendulum/fast:
	$(MAKE) -f examples/system_pendulum/CMakeFiles/system_pendulum.dir/build.make examples/system_pendulum/CMakeFiles/system_pendulum.dir/build
.PHONY : system_pendulum/fast

#=============================================================================
# Target rules for targets named first_order_general_adapt

# Build rule for target.
first_order_general_adapt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 first_order_general_adapt
.PHONY : first_order_general_adapt

# fast build rule for target.
first_order_general_adapt/fast:
	$(MAKE) -f examples/first_order_general_adapt/CMakeFiles/first_order_general_adapt.dir/build.make examples/first_order_general_adapt/CMakeFiles/first_order_general_adapt.dir/build
.PHONY : first_order_general_adapt/fast

#=============================================================================
# Target rules for targets named system_pendulum_adapt

# Build rule for target.
system_pendulum_adapt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_pendulum_adapt
.PHONY : system_pendulum_adapt

# fast build rule for target.
system_pendulum_adapt/fast:
	$(MAKE) -f examples/system_pendulum_adapt/CMakeFiles/system_pendulum_adapt.dir/build.make examples/system_pendulum_adapt/CMakeFiles/system_pendulum_adapt.dir/build
.PHONY : system_pendulum_adapt/fast

#=============================================================================
# Target rules for targets named laplace_bc_dirichlet_adapt

# Build rule for target.
laplace_bc_dirichlet_adapt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplace_bc_dirichlet_adapt
.PHONY : laplace_bc_dirichlet_adapt

# fast build rule for target.
laplace_bc_dirichlet_adapt/fast:
	$(MAKE) -f examples/laplace_bc_dirichlet_adapt/CMakeFiles/laplace_bc_dirichlet_adapt.dir/build.make examples/laplace_bc_dirichlet_adapt/CMakeFiles/laplace_bc_dirichlet_adapt.dir/build
.PHONY : laplace_bc_dirichlet_adapt/fast

#=============================================================================
# Target rules for targets named system_chaotic

# Build rule for target.
system_chaotic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_chaotic
.PHONY : system_chaotic

# fast build rule for target.
system_chaotic/fast:
	$(MAKE) -f examples/system_chaotic/CMakeFiles/system_chaotic.dir/build.make examples/system_chaotic/CMakeFiles/system_chaotic.dir/build
.PHONY : system_chaotic/fast

#=============================================================================
# Target rules for targets named system_car_model

# Build rule for target.
system_car_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_car_model
.PHONY : system_car_model

# fast build rule for target.
system_car_model/fast:
	$(MAKE) -f examples/system_car_model/CMakeFiles/system_car_model.dir/build.make examples/system_car_model/CMakeFiles/system_car_model.dir/build
.PHONY : system_car_model/fast

#=============================================================================
# Target rules for targets named legendre-1

# Build rule for target.
legendre-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 legendre-1
.PHONY : legendre-1

# fast build rule for target.
legendre-1/fast:
	$(MAKE) -f tests/legendre-1/CMakeFiles/legendre-1.dir/build.make tests/legendre-1/CMakeFiles/legendre-1.dir/build
.PHONY : legendre-1/fast

#=============================================================================
# Target rules for targets named legendre-2

# Build rule for target.
legendre-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 legendre-2
.PHONY : legendre-2

# fast build rule for target.
legendre-2/fast:
	$(MAKE) -f tests/legendre-2/CMakeFiles/legendre-2.dir/build.make tests/legendre-2/CMakeFiles/legendre-2.dir/build
.PHONY : legendre-2/fast

#=============================================================================
# Target rules for targets named lobatto-1

# Build rule for target.
lobatto-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lobatto-1
.PHONY : lobatto-1

# fast build rule for target.
lobatto-1/fast:
	$(MAKE) -f tests/lobatto-1/CMakeFiles/lobatto-1.dir/build.make tests/lobatto-1/CMakeFiles/lobatto-1.dir/build
.PHONY : lobatto-1/fast

#=============================================================================
# Target rules for targets named lobatto-2

# Build rule for target.
lobatto-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lobatto-2
.PHONY : lobatto-2

# fast build rule for target.
lobatto-2/fast:
	$(MAKE) -f tests/lobatto-2/CMakeFiles/lobatto-2.dir/build.make tests/lobatto-2/CMakeFiles/lobatto-2.dir/build
.PHONY : lobatto-2/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... hermes1d"
	@echo "... first_order_general"
	@echo "... laplace_bc_dirichlet"
	@echo "... laplace_bc_neumann"
	@echo "... laplace_bc_newton"
	@echo "... laplace_bc_newton2"
	@echo "... system_exp"
	@echo "... system_sin"
	@echo "... system_sin_adapt"
	@echo "... system_pendulum"
	@echo "... first_order_general_adapt"
	@echo "... system_pendulum_adapt"
	@echo "... laplace_bc_dirichlet_adapt"
	@echo "... system_chaotic"
	@echo "... system_car_model"
	@echo "... legendre-1"
	@echo "... legendre-2"
	@echo "... lobatto-1"
	@echo "... lobatto-2"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

